### ISSUE TITLE
Public link to my list of predictions

### ISSUE THREAD

**Issue by dreeves** [speezepearson/biatob#17]
I can already publicly link to any individual predictions.

Feature request: Let me link to all my predictions.

It would be especially nice if I could point people to biatob.com/dreev (in my case) instead of the uglier biatob.com/username/dreev. But currently neither of those work.

(Related opinion: I think everything should be public. You can always describe a prediction obscurely/cagily/esoterically if it's something sensitive. Also you can always add privacy later but you can't go the other direction, so it's good to start with everything-is-public to avoid being backed into any corners.)

**Comment by speezepearson** [comment]
Thanks for the input! Does https://biatob.com/u/dreev suit you?

**Comment by dreeves** [comment]
Beautiful! 

(I would like it epsilon better if the URL were biatob.com/dreev instead of biatob.com/u/dreev but i understand that that's implementationally tricky since you have to stake out part of the URL-space. I do think it's doable (Beeminder does it) by, for example, disallowing single-character usernames, which I also recommend (Beeminder didn't do that and I regret it).)

**Comment by speezepearson** [comment]
Yeah, I would also like that better. If there was a simple way to carve up URL-space into "reserved stuff for my use" vs "usernames," I would leap on it, but... I can't think of a rule that would put `/welcome`, `/login`, `/new`, and `/settings` on one side, and `/dreev` and `/spencer` on the other side.

Well, maybe I can just block some finite set of usernames (`welcome`, `login`, ...). And _maybe_ someday I'll want to add a new path and discover that that collides with some weird username that somebody chose, but that seems pretty unlikely, and not hard to recover from if it happens.

I'm inclined to do it! I'll sleep on it and implement it tomorrow, probably.

**Comment by dreeves** [comment]
That's what Beeminder did (and I'd be happy to show you the big list of slugs we staked out [and email sent]). Also note that you can just keep staking things out as you go because even when you have like 100k, users, I can assure you from experience that very few dictionary words will actually have been taken. I guess that's your point in your next paragraph.

Also-also I think a minimum of 3 characters for usernames is a good idea, for a few reasons (greppability, css/layout considerations, easier clickability when the username is a link, maybe just aesthetics, just the fact that you can always change your mind later and allow them but you can't go the other way, ...).
