### ISSUE TITLE
[feature] Let me sign up to get emailed when a bet resolves

### ISSUE THREAD

**Issue by orborde** [speezepearson/biatob#29]
Sometimes, I'm interested in the bet's outcome even if I don't have money on the line. Maybe I was too chicken to bet, maybe betting closed before I saw the bet, or maybe I didn't bet because I didn't want to take the bid or ask.

In these cases, I'd still like to get emailed when the bet resolves! A "subscribe" button on the bet page seems like a fine implementation.

**Comment by speezepearson** [comment]
Feature added, and deployed to production.
