### ISSUE TITLE
Embeddable prediction image is broken in preview

### ISSUE THREAD

**Issue by orborde** [speezepearson/biatob#8]
![image](https://user-images.githubusercontent.com/804638/112735987-99f0b280-8f0c-11eb-84e4-9ba1afaa547f.png)

This is on the preview at https://biatob.com/new . Notice the broken image link by the "This would render as" line.

**Comment by speezepearson** [comment]
Obsolete! The preview is no longer from the creator's perspective, so it doesn't include the embeddable image.
